### ISSUE TITLE
Unnecessary permission: "Allow this application to run when you are not present"

### ISSUE THREAD

**Issue by six5536** [krilor/heading-numbers#3]
Thanks for the great add-on.

The add-on requires the following permission when installed:
"Allow this application to run when you are not present"

This should not be necessary and is disconcerting. It looks like it is being added automatically because 'ScriptApp.AuthMode' is contained in the comments of 2 of the functions used. 

See:
https://stackoverflow.com/questions/48179449/allow-this-application-to-run-when-you-are-not-present-in-google-apps-script

It would be great if you could remove the comment and redeploy the app to the App Store without this permission.

**Comment by krilor** [comment]
Thanks for reporting this @relefant 

I've removed the comments and are waiting for Googles review team to approve it.

**Comment by krilor** [comment]
Changes has been approved.
Thanks again @relefant
